S905 Krypton 20170212

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -21,24 +21,24 @@
 ################################################################################
 
   # create directories
-  /bin/busybox mkdir -p /dev
-  /bin/busybox mkdir -p /proc
-  /bin/busybox mkdir -p /sys
-  /bin/busybox mkdir -p /tmp
-  /bin/busybox mkdir -p /flash
-  /bin/busybox mkdir -p /sysroot
-  /bin/busybox mkdir -p /storage
+  /usr/bin/busybox mkdir -p /dev
+  /usr/bin/busybox mkdir -p /proc
+  /usr/bin/busybox mkdir -p /sys
+  /usr/bin/busybox mkdir -p /tmp
+  /usr/bin/busybox mkdir -p /flash
+  /usr/bin/busybox mkdir -p /sysroot
+  /usr/bin/busybox mkdir -p /storage
 
   # mount all needed special filesystems
-  /bin/busybox mount -t devtmpfs devtmpfs /dev
-  /bin/busybox mount -t proc proc /proc
-  /bin/busybox mount -t sysfs sysfs /sys
+  /usr/bin/busybox mount -t devtmpfs devtmpfs /dev
+  /usr/bin/busybox mount -t proc proc /proc
+  /usr/bin/busybox mount -t sysfs sysfs /sys
 
   # common functions
   . /functions
 
   # set needed variables
-  MODULE_DIR=/lib/modules
+  MODULE_DIR=/usr/lib/modules
 
   UPDATE_ROOT=/storage/.update
   UPDATE_DIR="$UPDATE_ROOT"
@@ -52,6 +52,7 @@
   MD5_FAILED="0"
   RUN_FSCK="yes"
   RUN_FSCK_DISKS=""
+  SYSLINUX_DEFAULT=""
 
   NBD_DEVS="0"
   FLASH_FREE_MIN="5"
@@ -60,6 +61,10 @@
   SYSTEM_TORAM_LIMIT=1024000
 
   LIVE="no"
+
+  # Get a serial number if present (eg. RPi) otherwise use MAC address from eth0
+  MACHINE_UID="$(cat /proc/cpuinfo | awk '/^Serial/{s=$3; gsub ("^0*","",s); print s}')"
+  [ -z "$MACHINE_UID" ] && MACHINE_UID="$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d :)"
 
   # hide kernel log messages on console
   echo '1 4 1 7' > /proc/sys/kernel/printk
@@ -121,6 +126,7 @@
         ;;
       installer)
         INIT_UNIT="--unit=installer.target"
+        SYSLINUX_DEFAULT="installer"
         ;;
       debugging)
         DEBUG=yes
@@ -140,9 +146,17 @@
         ;;
       live)
         LIVE=yes
+        SYSLINUX_DEFAULT="live"
+        ;;
+      portable)
+        SYSLINUX_DEFAULT="run"
         ;;
       overlay)
         OVERLAY=yes
+        ;;
+      setfbres=*)
+        SWITCH_FRAMEBUFFER="${arg#*=}"
+        SWITCH_FRAMEBUFFER="${SWITCH_FRAMEBUFFER//,/ }"
         ;;
       break=*)
         BREAK="${arg#*=}"
@@ -159,8 +173,12 @@
 
   progress() {
     if test "$PROGRESS" = "yes"; then
-      echo "### $1 ###"
+      echo "### $1 ###" >&2
     fi
+  }
+
+  debug_msg() {
+    echo "$1" >&$SILENT_OUT
   }
 
   debug_shell() {
@@ -174,7 +192,7 @@
   error() {
     # Display fatal error message
     # $1:action which caused error, $2:message
-    echo "*** Error in $BOOT_STEP: $1: $2 ***"
+    echo "*** Error in $BOOT_STEP: $1: $2 ***" >&2
     debug_shell
   }
 
@@ -190,7 +208,6 @@
   # Mount handlers
   # All handlers take the following parameters:
   # $1:target, $2:mountpoint, $3:mount options, [$4:fs type]
-
   mount_common() {
     # Common mount handler, handles block devices and filesystem images
     MOUNT_OPTIONS="-o $3"
@@ -254,19 +271,19 @@
     ISCSI_DEV="${1##*,}"
     ISCSI_OPTIONS="${1%,*}"
 
-    if [ ! -f "/sbin/iscsistart" ]; then
+    if [ ! -f "/usr/sbin/iscsistart" ]; then
       error "iscsistart" "iSCSI support not available"
     fi
 
     if [ "$ISCSI_OPTIONS" = "auto" ]; then
       progress "Network configuration based on iBFT"
-      /sbin/iscsistart -N >&$SILENT_OUT 2>&1 || \
+      /usr/sbin/iscsistart -N >&$SILENT_OUT 2>&1 || \
         error "iscsistart" "Unable to configure network"
       progress "iSCSI auto connect based on iBFT"
-      /sbin/iscsistart -b >&$SILENT_OUT 2>&1 || \
+      /usr/sbin/iscsistart -b >&$SILENT_OUT 2>&1 || \
         error "iscsistart" "Unable to auto connect"
     else
-      /sbin/iscsistart $(get_iscsistart_options "$ISCSI_OPTIONS") >&$SILENT_OUT 2>&1 || \
+      /usr/sbin/iscsistart $(get_iscsistart_options "$ISCSI_OPTIONS") >&$SILENT_OUT 2>&1 || \
         error "iscsistart" "Unable to connect to ISCSI target"
     fi
 
@@ -330,7 +347,72 @@
         error "mount_part" "Unknown filesystem $1"
         ;;
     esac
+
+    # Substitute unique identifier if available or remove placeholder
+    MOUNT_TARGET="${MOUNT_TARGET//@UID@/$MACHINE_UID}"
+
     $MOUNT_CMD "$MOUNT_TARGET" "$2" "$3" "$4"
+  }
+
+  # mount the specified SYSTEM file and output arch from /etc/os-release
+  get_project_arch() {
+    mount_part "$1" "/sysroot" "ro,loop"
+
+    if [ -f /sysroot/etc/os-release ]; then
+      . /sysroot/etc/os-release
+      echo "${LIBREELEC_ARCH:-${OPENELEC_ARCH}}"
+    fi
+
+    umount /sysroot
+  }
+
+  # If the project/arch of current matches the upgrade, then it is considered compatible.
+  # Otherwise, mount the upgrade SYSTEM partition and, if canupdate.sh is available,
+  # call the script to determine if the current upgrade file can be applied on to the
+  # current system - 0 means it is compatible, non-zero that it is not compatible.
+  is_compatible() {
+    local result=1
+
+    if [ "${2}" = "${3}" ]; then
+      result=0
+    else
+      mount_part "$1" "/sysroot" "ro,loop"
+
+      if [ -f /sysroot/usr/share/bootloader/canupdate.sh ]; then
+        sh /sysroot/usr/share/bootloader/canupdate.sh "${2}" "${3}" && result=0
+      fi
+
+      umount /sysroot
+    fi
+
+    return ${result}
+  }
+
+  # determine if the new SYSTEM file is compatible with the current SYSTEM file
+  check_is_compatible() {
+    local update_filename="${1}"
+    local old_system="${2}"
+    local new_system="${3}"
+    local old_project_arch="$(get_project_arch "${old_system}")"
+    local new_project_arch="$(get_project_arch "${new_system}")"
+
+    # If old or new project/arch isn't available then could be very old (pre-/etc/os-release) build - have to trust it
+    if [ -n "${old_project_arch}" -a -n "${new_project_arch}" ]; then
+      # If the old project/arch is not compatible with the new project/arch then abort...
+      if ! is_compatible "${new_system}" "${old_project_arch}" "${new_project_arch}"; then
+        echo ""
+        echo "ERROR: $(basename "${update_filename}") is not compatible with ${old_project_arch} hardware - update cancelled."
+        echo ""
+        echo "Current system: ${old_project_arch}"
+        echo "Update  system: ${new_project_arch}"
+        echo ""
+        echo "Create $UPDATE_ROOT/.nocompat to disable compatibility checks and risk a non-booting system."
+        echo ""
+        return 1
+      fi
+    fi
+
+    return 0
   }
 
   update_file() {
@@ -358,7 +440,7 @@
 
     if [ -f "$UPDATE_DIR/$2" -a -b "$3" ]; then
       StartProgress spinner "Updating $1... "
-        result="$(dd if="$UPDATE_DIR/$2" of="$3" bs=64K conv=fsync 2>&1)"
+        result="$(dd if="$UPDATE_DIR/$2" of="$3" conv=fsync 2>&1)"
         StopProgress "done"
       echo "${result}"
     fi
@@ -395,33 +477,72 @@
   }
 
   load_splash() {
+    local set_default_res=no
+    local vres
+
     if [ ! "$SPLASH" = "no" ]; then
       progress "Loading bootsplash"
-
-      SPLASHIMAGE="/splash/splash-full.png"
 
       # load uvesafb module if needed
       if [ -f "$MODULE_DIR/uvesafb.ko" -a ! -e /dev/fb0 ]; then
         progress "Loading kernel module uvesafb.ko"
-        insmod "$MODULE_DIR/uvesafb.ko" || \
+        insmod "$MODULE_DIR/uvesafb.ko" && \
+          set_default_res=yes || \
           progress "... Failed to load kernel module uvesafb, skipping"
-
-        # set framebuffer to a default resolution (1024x768-32)
-        if [ ! "$SWITCH_FRAMEBUFFER" = "no" ]; then
-          fbset -g 1024 768 1024 768 32
-          SPLASHIMAGE="/splash/splash-1024.png"
-        fi
       fi
 
       if [ -e /dev/fb0 ]; then
+        # Set framebuffer to a custom resolution and/or fallback to default resolution (1024x768-32), if required.
+        if [ ! "$SWITCH_FRAMEBUFFER" = "no" ]; then
+          if [ "$SWITCH_FRAMEBUFFER" = "1080" ]; then
+            SWITCH_FRAMEBUFFER="1920 1080 1920 1080 32"
+          elif [ "$SWITCH_FRAMEBUFFER" = "720" ]; then
+            SWITCH_FRAMEBUFFER="1280 720 1280 720 32"
+          fi
+
+          # Try setting a custom framebuffer resolution
+          if [ ! "${SWITCH_FRAMEBUFFER:-yes}" = "yes" ]; then
+            fbset -g $SWITCH_FRAMEBUFFER 2>/dev/null && set_default_res=no
+          fi
+
+          # Set a default resolution if required
+          if [ "$set_default_res" = "yes" ]; then
+            fbset -g 1024 768 1024 768 32
+          fi
+        fi
+
         # load splash
-        if [ -f /flash/oemsplash.png ]; then
-          SPLASHIMAGE="/flash/oemsplash.png"
-        elif [ -f /splash/splash.conf ]; then
+        if [ -f /splash/splash.conf ]; then
           . /splash/splash.conf
         fi
 
-        ply-image $SPLASHIMAGE > /dev/null 2>&1
+        # Select splash image based on current native resolution
+        if [ -z "$SPLASHIMAGE" ]; then
+          vres="$(fbset 2>/dev/null | awk '/geometry/ { print $3 }')"
+
+          if [ -f /flash/oemsplash.png -o -f /flash/oemsplash-1080.png ]; then
+            if [ -n "$vres" -a -f /flash/oemsplash-$vres.png ]; then
+              SPLASHIMAGE="/flash/oemsplash-$vres.png"
+            elif [ -f /flash/oemsplash-1080.png ]; then
+              SPLASHIMAGE="/flash/oemsplash-1080.png"
+            else
+              SPLASHIMAGE="/flash/oemsplash.png"
+            fi
+          else
+            if [ -n "$vres" -a -f /splash/splash-$vres.png ]; then
+              SPLASHIMAGE="/splash/splash-$vres.png"
+            else
+              SPLASHIMAGE="/splash/splash-1080.png"
+            fi
+          fi
+        fi
+
+        if [ -n "$SPLASHIMAGE" -a -f "$SPLASHIMAGE" ]; then
+          ply-image $SPLASHIMAGE > /dev/null 2>&1
+        fi
+
+        debug_msg "Framebuffer vertical res: $vres"
+        debug_msg "Framebuffer splash image: $SPLASHIMAGE"
       fi
     fi
   }
@@ -433,16 +554,16 @@
     sync
 
     # unmount filesystems
-    if /bin/busybox mountpoint -q /flash ; then
-      /bin/busybox umount /flash
+    if /usr/bin/busybox mountpoint -q /flash ; then
+      /usr/bin/busybox umount /flash
     fi
 
-    if /bin/busybox mountpoint -q /storage ; then
-      /bin/busybox umount /storage
+    if /usr/bin/busybox mountpoint -q /storage ; then
+      /usr/bin/busybox umount /storage
     fi
 
     usleep 2000000
-    /bin/busybox reboot
+    /usr/bin/busybox reboot
   }
 
   force_fsck() {
@@ -456,7 +577,7 @@
     if [ "$?" -ne "0" -o "$?" -gt "128" ] ; then
       echo "Repairing filesystem..."
       echo ""
-      /sbin/fsck -T -M -y $RUN_FSCK_DISKS
+      /usr/sbin/fsck -T -M -y $RUN_FSCK_DISKS
       FSCK_RET="$?"
       if [ "$(( $FSCK_RET & 8 ))" = 8 ] ; then
         # fubar
@@ -480,7 +601,7 @@
   check_disks() {
     if [ "$RUN_FSCK" = "yes" -a -n "$RUN_FSCK_DISKS" ]; then
       progress "Checking disk(s): $RUN_FSCK_DISKS"
-      /sbin/fsck -T -M -p -a $RUN_FSCK_DISKS > /dev/null 2>&1
+      /usr/sbin/fsck -T -M -p -a $RUN_FSCK_DISKS > /dev/null 2>&1
       FSCK_RET="$?"
 
       # FSCK_RET is the bit-wise OR of the exit codes for each filesystem that is checked.
@@ -565,6 +686,43 @@
     fi
   }
 
+  # Make last bootloader label (installer, live, run etc.) as the new default
+  update_syslinux() {
+    local crnt_default
+
+    if [ -n "$SYSLINUX_DEFAULT" -a -f /flash/syslinux.cfg ]; then
+      if grep -q "^LABEL $SYSLINUX_DEFAULT\$" /flash/syslinux.cfg; then
+        crnt_default="$(awk '/^DEFAULT/ {print $2}' /flash/syslinux.cfg)"
+        if [ ! "$crnt_default" = "$SYSLINUX_DEFAULT" ]; then
+          progress "Updating /flash/syslinux.cfg [$crnt_default -> $SYSLINUX_DEFAULT]"
+
+          mount -o remount,rw /flash
+          sed -i "s/^DEFAULT .*/DEFAULT $SYSLINUX_DEFAULT/" /flash/syslinux.cfg
+          [ -f /flash/EFI/BOOT/syslinux.cfg ] && cp /flash/syslinux.cfg /flash/EFI/BOOT/syslinux.cfg
+          mount -o remount,ro /flash
+        fi
+      fi
+    fi
+  }
+
+  check_out_of_space() {
+    if [ "$(df /storage | awk '/[0-9]%/{print $4}')" -eq "0" ]; then
+      echo ""
+      echo "The $1 is corrupt, or there is not enough"
+      echo "free space on /storage to complete the upgrade!"
+      echo ""
+      echo "Please free up space on your /storage partition"
+      echo "by deleting unecessary files, then try again."
+      echo ""
+      return 0
+    else
+      echo ""
+      echo "The $1 is corrupt/invalid!"
+      echo ""
+      return 1
+    fi
+  }
+
   do_cleanup() {
     StartProgress spinner "Cleaning up... "
 
@@ -583,6 +741,7 @@
 
     rm -rf $UPDATE_ROOT/.tmp &>/dev/null
     rm -rf $UPDATE_ROOT/[0-9a-zA-Z]* &>/dev/null
+    rm -f  $UPDATE_ROOT/.nocheck $UPDATE_ROOT/.nocompat &>/dev/null
 
     sync
 
@@ -616,13 +775,30 @@
     echo ""
 
     if [ -f "$UPDATE_TAR" ] ; then
+      TARRESULT="0"
+
       echo "Found new .tar archive"
+      UPDATE_FILENAME="$UPDATE_TAR"
       StartProgress spinner "Extracting contents of archive... "
         mkdir -p $UPDATE_DIR/.tmp &>/dev/null
-        tar -xf "$UPDATE_TAR" -C $UPDATE_DIR/.tmp &>/dev/null
+        tar -xf "$UPDATE_TAR" -C $UPDATE_DIR/.tmp 1>/dev/null 2>/tmp/tarresult.txt || TARRESULT="1"
+
+      if [ "${TARRESULT}" -eq "0" ]; then
         mv $UPDATE_DIR/.tmp/*/target/* $UPDATE_DIR &>/dev/null
         sync
         StopProgress "done"
+      else
+        StopProgress "FAILED"
+
+        echo "Failed to extract contents of archive file!"
+        echo "tar result: '$(cat /tmp/tarresult.txt)'"
+
+        check_out_of_space "archive"
+
+        do_cleanup
+        StartProgress countdown "Normal startup in 30s... " 30 "NOW"
+        return 0
+      fi
     elif [ -f "$UPDATE_IMG_GZ" -o -f "$UPDATE_IMG" ] ; then
       mkdir -p $UPDATE_DIR/.tmp/mnt &>/dev/null
       IMG_FILE="$UPDATE_DIR/.tmp/update.img"
@@ -630,7 +806,7 @@
 
       if [ -f "$UPDATE_IMG_GZ" ]; then
         echo "Found new compressed image file"
-
+        UPDATE_FILENAME="$UPDATE_IMG_GZ"
         StartProgress spinner "Decompressing image file... "
           gunzip -d -c "$UPDATE_IMG_GZ" 1>$IMG_FILE 2>/tmp/gzresult.txt || GZRESULT="1"
           sync
@@ -639,12 +815,16 @@
         if [ "${GZRESULT}" -eq "1" ]; then
           echo "Failed to decompress image file!"
           echo "gunzip result: '$(cat /tmp/gzresult.txt)'"
+
+          check_out_of_space "compressed image"
+
           do_cleanup
           StartProgress countdown "Normal startup in 30s... " 30 "NOW"
           return 0
         fi
       else
         echo "Found new image file"
+        UPDATE_FILENAME="$UPDATE_IMG"
         mv "$UPDATE_IMG" $IMG_FILE
       fi
 
@@ -685,6 +865,8 @@
       else
         UPDATE_KERNEL="@KERNEL_NAME@"
       fi
+    else
+      UPDATE_FILENAME="$UPDATE_DIR/$UPDATE_SYSTEM"
     fi
 
     sync
@@ -697,7 +879,7 @@
     fi
 
     # check md5 sums if .nocheck doesn't exist
-    if [ ! -f "$UPDATE_DIR/.nocheck" ]; then
+    if [ ! -f "$UPDATE_ROOT/.nocheck" ]; then
       if [ -f "$UPDATE_DIR/${UPDATE_KERNEL}.md5" -a -f "$UPDATE_DIR/${UPDATE_SYSTEM}.md5" ] ; then
         # *.md5 size-check
         if [ ! -s "$UPDATE_DIR/${UPDATE_KERNEL}.md5" -o ! -s "$UPDATE_DIR/${UPDATE_SYSTEM}.md5" ] ; then
@@ -713,7 +895,7 @@
             else
               StopProgress "FAILED"
               MD5_FAILED="1"
-	    fi
+            fi
 
           StartProgress spinner "Checking ${UPDATE_SYSTEM}.md5... "
             if md5sum -sc "$UPDATE_ROOT/${UPDATE_SYSTEM}.check.md5"; then
@@ -736,6 +918,16 @@
       fi
     fi
 
+    # Verify that the new upgrade is compatible with the current system - this should avoid creating
+    # non-booting systems after (for example) an RPi tar is incorrectly applied to an RPi2 system.
+    if [ ! -f "$UPDATE_ROOT/.nocompat" ]; then
+      if ! check_is_compatible "$UPDATE_FILENAME" "/flash/$IMAGE_SYSTEM" "$UPDATE_DIR/$UPDATE_SYSTEM"; then
+        do_cleanup
+        StartProgress countdown "Normal startup in 60s... " 60 "NOW"
+        return 0
+      fi
+    fi
+
     # get sizes
     FLASH_FREE=$(df /flash/ | awk '/[0-9]%/{print $4}')
     FLASH_FREE=$(( $FLASH_FREE * 1024 ))
@@ -751,7 +943,7 @@
     NEW_KERNEL=$(stat -t "$UPDATE_DIR/$UPDATE_KERNEL" | awk '{print $2}')
     NEW_SYSTEM=$(stat -t "$UPDATE_DIR/$UPDATE_SYSTEM" | awk '{print $2}')
 
-    # old KERNEL+SYSTEM+free space - new KERNEL+SYSTEM must be higher then 5MB
+    # old KERNEL+SYSTEM+free space - new KERNEL+SYSTEM must be higher than 5MB
     # at least 5MB free after update
 
     TMP_SIZE=$(($OLD_KERNEL+$OLD_SYSTEM+$FLASH_FREE-$NEW_KERNEL-$NEW_SYSTEM))
@@ -799,7 +991,7 @@
     mount --move /flash /sysroot/flash
     mount --move /storage /sysroot/storage
 
-    if [ ! -d "/sysroot/lib/modules/$(uname -r)/" -a -f "/sysroot/usr/lib/systemd/systemd" ]; then
+    if [ ! -d "/sysroot/usr/lib/modules/$(uname -r)/" -a -f "/sysroot/usr/lib/systemd/systemd" ]; then
       echo ""
       echo "NEVER TOUCH boot= in extlinux.conf / cmdline.txt!"
       echo "If you don't know what you are doing,"
@@ -853,11 +1045,14 @@
     error "check arguments" "boot argument can't be FILE type..."
   fi
 
+  debug_msg "Unique identifier for this client: ${MACHINE_UID:-NOT AVAILABLE}"
+
   # main boot sequence
   for BOOT_STEP in \
       load_modules \
       check_disks \
       mount_flash \
+      update_syslinux \
       load_splash \
       mount_storage \
       check_update \
@@ -884,10 +1079,10 @@
     fi
   done
   # move some special filesystems
-  /bin/busybox mount --move /dev /sysroot/dev
-  /bin/busybox mount --move /proc /sysroot/proc
-  /bin/busybox mount --move /sys /sysroot/sys
-  /bin/busybox rm -fr /tmp
+  /usr/bin/busybox mount --move /dev /sysroot/dev
+  /usr/bin/busybox mount --move /proc /sysroot/proc
+  /usr/bin/busybox mount --move /sys /sysroot/sys
+  /usr/bin/busybox rm -fr /tmp
 
   # tell OE settings addon to disable updates
   if [ "$UPDATE_DISABLED" = "yes" ] ; then
@@ -912,6 +1107,6 @@
   fi
 
   # switch to new sysroot and start real init
-  exec /bin/busybox switch_root /sysroot /usr/lib/systemd/systemd $INIT_ARGS $INIT_UNIT
+  exec /usr/bin/busybox switch_root /sysroot /usr/lib/systemd/systemd $INIT_ARGS $INIT_UNIT
 
   error "switch_root" "Error in initramfs. Could not switch to new root"
