Krypton 20161205

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -52,6 +52,7 @@
   MD5_FAILED="0"
   RUN_FSCK="yes"
   RUN_FSCK_DISKS=""
+  SYSLINUX_DEFAULT=""
 
   NBD_DEVS="0"
   FLASH_FREE_MIN="5"
@@ -60,6 +61,10 @@
   SYSTEM_TORAM_LIMIT=1024000
 
   LIVE="no"
+
+  # Get a serial number if present (eg. RPi) otherwise use MAC address from eth0
+  MACHINE_UID="$(cat /proc/cpuinfo | awk '/^Serial/{s=$3; gsub ("^0*","",s); print s}')"
+  [ -z "$MACHINE_UID" ] && MACHINE_UID="$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d :)"
 
   # hide kernel log messages on console
   echo '1 4 1 7' > /proc/sys/kernel/printk
@@ -121,6 +126,7 @@
         ;;
       installer)
         INIT_UNIT="--unit=installer.target"
+        SYSLINUX_DEFAULT="installer"
         ;;
       debugging)
         DEBUG=yes
@@ -140,6 +146,10 @@
         ;;
       live)
         LIVE=yes
+        SYSLINUX_DEFAULT="live"
+        ;;
+      portable)
+        SYSLINUX_DEFAULT="run"
         ;;
       overlay)
         OVERLAY=yes
@@ -163,7 +173,7 @@
 
   progress() {
     if test "$PROGRESS" = "yes"; then
-      echo "### $1 ###"
+      echo "### $1 ###" >&2
     fi
   }
 
@@ -182,7 +192,7 @@
   error() {
     # Display fatal error message
     # $1:action which caused error, $2:message
-    echo "*** Error in $BOOT_STEP: $1: $2 ***"
+    echo "*** Error in $BOOT_STEP: $1: $2 ***" >&2
     debug_shell
   }
 
@@ -198,7 +208,6 @@
   # Mount handlers
   # All handlers take the following parameters:
   # $1:target, $2:mountpoint, $3:mount options, [$4:fs type]
-
   mount_common() {
     # Common mount handler, handles block devices and filesystem images
     MOUNT_OPTIONS="-o $3"
@@ -338,7 +347,72 @@
         error "mount_part" "Unknown filesystem $1"
         ;;
     esac
+
+    # Substitute unique identifier if available or remove placeholder
+    MOUNT_TARGET="${MOUNT_TARGET//@UID@/$MACHINE_UID}"
+
     $MOUNT_CMD "$MOUNT_TARGET" "$2" "$3" "$4"
+  }
+
+  # mount the specified SYSTEM file and output arch from /etc/os-release
+  get_project_arch() {
+    mount_part "$1" "/sysroot" "ro,loop"
+
+    if [ -f /sysroot/etc/os-release ]; then
+      . /sysroot/etc/os-release
+      echo "${LIBREELEC_ARCH:-${OPENELEC_ARCH}}"
+    fi
+
+    umount /sysroot
+  }
+
+  # If the project/arch of current matches the upgrade, then it is considered compatible.
+  # Otherwise, mount the upgrade SYSTEM partition and, if canupdate.sh is available,
+  # call the script to determine if the current upgrade file can be applied on to the
+  # current system - 0 means it is compatible, non-zero that it is not compatible.
+  is_compatible() {
+    local result=1
+
+    if [ "${2}" = "${3}" ]; then
+      result=0
+    else
+      mount_part "$1" "/sysroot" "ro,loop"
+
+      if [ -f /sysroot/usr/share/bootloader/canupdate.sh ]; then
+        sh /sysroot/usr/share/bootloader/canupdate.sh "${2}" "${3}" && result=0
+      fi
+
+      umount /sysroot
+    fi
+
+    return ${result}
+  }
+
+  # determine if the new SYSTEM file is compatible with the current SYSTEM file
+  check_is_compatible() {
+    local update_filename="${1}"
+    local old_system="${2}"
+    local new_system="${3}"
+    local old_project_arch="$(get_project_arch "${old_system}")"
+    local new_project_arch="$(get_project_arch "${new_system}")"
+
+    # If old or new project/arch isn't available then could be very old (pre-/etc/os-release) build - have to trust it
+    if [ -n "${old_project_arch}" -a -n "${new_project_arch}" ]; then
+      # If the old project/arch is not compatible with the new project/arch then abort...
+      if ! is_compatible "${new_system}" "${old_project_arch}" "${new_project_arch}"; then
+        echo ""
+        echo "ERROR: $(basename "${update_filename}") is not compatible with ${old_project_arch} hardware - update cancelled."
+        echo ""
+        echo "Current system: ${old_project_arch}"
+        echo "Update  system: ${new_project_arch}"
+        echo ""
+        echo "Create $UPDATE_ROOT/.nocompat to disable compatibility checks and risk a non-booting system."
+        echo ""
+        return 1
+      fi
+    fi
+
+    return 0
   }
 
   update_file() {
@@ -612,6 +686,43 @@
     fi
   }
 
+  # Make last bootloader label (installer, live, run etc.) as the new default
+  update_syslinux() {
+    local crnt_default
+
+    if [ -n "$SYSLINUX_DEFAULT" -a -f /flash/syslinux.cfg ]; then
+      if grep -q "^LABEL $SYSLINUX_DEFAULT\$" /flash/syslinux.cfg; then
+        crnt_default="$(awk '/^DEFAULT/ {print $2}' /flash/syslinux.cfg)"
+        if [ ! "$crnt_default" = "$SYSLINUX_DEFAULT" ]; then
+          progress "Updating /flash/syslinux.cfg [$crnt_default -> $SYSLINUX_DEFAULT]"
+
+          mount -o remount,rw /flash
+          sed -i "s/^DEFAULT .*/DEFAULT $SYSLINUX_DEFAULT/" /flash/syslinux.cfg
+          [ -f /flash/EFI/BOOT/syslinux.cfg ] && cp /flash/syslinux.cfg /flash/EFI/BOOT/syslinux.cfg
+          mount -o remount,ro /flash
+        fi
+      fi
+    fi
+  }
+
+  check_out_of_space() {
+    if [ "$(df /storage | awk '/[0-9]%/{print $4}')" -eq "0" ]; then
+      echo ""
+      echo "The $1 is corrupt, or there is not enough"
+      echo "free space on /storage to complete the upgrade!"
+      echo ""
+      echo "Please free up space on your /storage partition"
+      echo "by deleting unecessary files, then try again."
+      echo ""
+      return 0
+    else
+      echo ""
+      echo "The $1 is corrupt/invalid!"
+      echo ""
+      return 1
+    fi
+  }
+
   do_cleanup() {
     StartProgress spinner "Cleaning up... "
 
@@ -630,6 +741,7 @@
 
     rm -rf $UPDATE_ROOT/.tmp &>/dev/null
     rm -rf $UPDATE_ROOT/[0-9a-zA-Z]* &>/dev/null
+    rm -f  $UPDATE_ROOT/.nocheck $UPDATE_ROOT/.nocompat &>/dev/null
 
     sync
 
@@ -663,13 +775,30 @@
     echo ""
 
     if [ -f "$UPDATE_TAR" ] ; then
+      TARRESULT="0"
+
       echo "Found new .tar archive"
+      UPDATE_FILENAME="$UPDATE_TAR"
       StartProgress spinner "Extracting contents of archive... "
         mkdir -p $UPDATE_DIR/.tmp &>/dev/null
-        tar -xf "$UPDATE_TAR" -C $UPDATE_DIR/.tmp &>/dev/null
+        tar -xf "$UPDATE_TAR" -C $UPDATE_DIR/.tmp 1>/dev/null 2>/tmp/tarresult.txt || TARRESULT="1"
+
+      if [ "${TARRESULT}" -eq "0" ]; then
         mv $UPDATE_DIR/.tmp/*/target/* $UPDATE_DIR &>/dev/null
         sync
         StopProgress "done"
+      else
+        StopProgress "FAILED"
+
+        echo "Failed to extract contents of archive file!"
+        echo "tar result: '$(cat /tmp/tarresult.txt)'"
+
+        check_out_of_space "archive"
+
+        do_cleanup
+        StartProgress countdown "Normal startup in 30s... " 30 "NOW"
+        return 0
+      fi
     elif [ -f "$UPDATE_IMG_GZ" -o -f "$UPDATE_IMG" ] ; then
       mkdir -p $UPDATE_DIR/.tmp/mnt &>/dev/null
       IMG_FILE="$UPDATE_DIR/.tmp/update.img"
@@ -677,7 +806,7 @@
 
       if [ -f "$UPDATE_IMG_GZ" ]; then
         echo "Found new compressed image file"
-
+        UPDATE_FILENAME="$UPDATE_IMG_GZ"
         StartProgress spinner "Decompressing image file... "
           gunzip -d -c "$UPDATE_IMG_GZ" 1>$IMG_FILE 2>/tmp/gzresult.txt || GZRESULT="1"
           sync
@@ -686,12 +815,16 @@
         if [ "${GZRESULT}" -eq "1" ]; then
           echo "Failed to decompress image file!"
           echo "gunzip result: '$(cat /tmp/gzresult.txt)'"
+
+          check_out_of_space "compressed image"
+
           do_cleanup
           StartProgress countdown "Normal startup in 30s... " 30 "NOW"
           return 0
         fi
       else
         echo "Found new image file"
+        UPDATE_FILENAME="$UPDATE_IMG"
         mv "$UPDATE_IMG" $IMG_FILE
       fi
 
@@ -732,6 +865,8 @@
       else
         UPDATE_KERNEL="@KERNEL_NAME@"
       fi
+    else
+      UPDATE_FILENAME="$UPDATE_DIR/$UPDATE_SYSTEM"
     fi
 
     sync
@@ -744,7 +879,7 @@
     fi
 
     # check md5 sums if .nocheck doesn't exist
-    if [ ! -f "$UPDATE_DIR/.nocheck" ]; then
+    if [ ! -f "$UPDATE_ROOT/.nocheck" ]; then
       if [ -f "$UPDATE_DIR/${UPDATE_KERNEL}.md5" -a -f "$UPDATE_DIR/${UPDATE_SYSTEM}.md5" ] ; then
         # *.md5 size-check
         if [ ! -s "$UPDATE_DIR/${UPDATE_KERNEL}.md5" -o ! -s "$UPDATE_DIR/${UPDATE_SYSTEM}.md5" ] ; then
@@ -760,7 +895,7 @@
             else
               StopProgress "FAILED"
               MD5_FAILED="1"
-	    fi
+            fi
 
           StartProgress spinner "Checking ${UPDATE_SYSTEM}.md5... "
             if md5sum -sc "$UPDATE_ROOT/${UPDATE_SYSTEM}.check.md5"; then
@@ -783,6 +918,16 @@
       fi
     fi
 
+    # Verify that the new upgrade is compatible with the current system - this should avoid creating
+    # non-booting systems after (for example) an RPi tar is incorrectly applied to an RPi2 system.
+    if [ ! -f "$UPDATE_ROOT/.nocompat" ]; then
+      if ! check_is_compatible "$UPDATE_FILENAME" "/flash/$IMAGE_SYSTEM" "$UPDATE_DIR/$UPDATE_SYSTEM"; then
+        do_cleanup
+        StartProgress countdown "Normal startup in 60s... " 60 "NOW"
+        return 0
+      fi
+    fi
+
     # get sizes
     FLASH_FREE=$(df /flash/ | awk '/[0-9]%/{print $4}')
     FLASH_FREE=$(( $FLASH_FREE * 1024 ))
@@ -798,7 +943,7 @@
     NEW_KERNEL=$(stat -t "$UPDATE_DIR/$UPDATE_KERNEL" | awk '{print $2}')
     NEW_SYSTEM=$(stat -t "$UPDATE_DIR/$UPDATE_SYSTEM" | awk '{print $2}')
 
-    # old KERNEL+SYSTEM+free space - new KERNEL+SYSTEM must be higher then 5MB
+    # old KERNEL+SYSTEM+free space - new KERNEL+SYSTEM must be higher than 5MB
     # at least 5MB free after update
 
     TMP_SIZE=$(($OLD_KERNEL+$OLD_SYSTEM+$FLASH_FREE-$NEW_KERNEL-$NEW_SYSTEM))
@@ -862,11 +1007,14 @@
     error "check arguments" "boot argument can't be FILE type..."
   fi
 
+  debug_msg "Unique identifier for this client: ${MACHINE_UID:-NOT AVAILABLE}"
+
   # main boot sequence
   for BOOT_STEP in \
       load_modules \
       check_disks \
       mount_flash \
+      update_syslinux \
       load_splash \
       mount_storage \
       check_update \
